name: Build and Push Flask App with Podman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Debug - List files in the repository to check Dockerfile location
      - name: Debug - List Files in Runner
        run: ls -R ${{ github.workspace }}

      # Step 3: Install Podman
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          podman --version

      # Step 4: Build Flask App Image using Podman
      - name: Build Flask App Image
        run: |
          podman build -t flask-app -f Dockerfile .

      # Step 5: Log in to Docker Hub using Podman
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | podman login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io

      # Step 6: Tag and Push Image to Docker Hub
      - name: Tag and Push Image
        run: |
          podman tag flask-app docker.io/${{ secrets.DOCKER_HUB_USERNAME

